- hosts: localhost
  user: root
  tasks:
  - name: nginx install
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: nginx service start
    service:
      name: nginx
      enabled: yes
